export const domains = [
	'storage.googleapis.com',
	'd3t3ozftmdmh3i.cloudfront.net',
	'd3wo5wojvuv7l.cloudfront.net',
	'www.omnycontent.com',
	'image.simplecastcdn.com',
	'jovemnerd.com.br',
	'ssl-static.libsyn.com',
	'99vidas.com.br',
	'media.blubrry.com',
	'assets.vercel.com',
	'flowpodcast.com.br',
	'artworks-flow.s3-sa-east-1.amazonaws.com',
	'creators-artworks.s3.sa-east-1.amazonaws.com',
]
